all:
  hosts:
    node2:
      ansible_host: 10.10.1.3
      ip: 10.10.1.3
      access_ip: 10.10.1.3
    node3:
      ansible_host: 10.10.1.4
      ip: 10.10.1.4
      access_ip: 10.10.1.4
    node1:
      ansible_host: 10.10.1.2
      ip: 10.10.1.2
      access_ip: 10.10.1.2
    node4:
      ansible_host: 10.10.1.5
      ip: 10.10.1.5
      access_ip: 10.10.1.5
  vars:
    ansible_user: loc_ansible
  children:
    k8s-cluster:
      children:
        kube-node:
        kube-master:
    kube-node:
      hosts:
        node2:
        node3:
        node1:
        node4:
    etcd:
      hosts:
        node2:
        node3:
        node1:
    calico-rr:
      hosts:
    kube-master:
      hosts:
        node2:
        node1:
